### ISSUE TITLE
just kill code package

### ISSUE THREAD

**Issue by SatCat** [suchipi/without-comments#1]
test part of code:
_________________________________________________________
// line comment
someValue
another value bla bla bla
val /* sdsd */ var = "\/\//", morevar='code//code'   //isn't that nice

var d = "http://some.site/offffcoseeeeeremoved-url";

        anotherOne
________________________________________________________
run:
 npx without-comments --token '//' ./stuff.txt

**Comment by suchipi** [comment]
Hello,

There is not enough information here to understand the problem you are facing. Additionally, it appears that GitHub's markdown formatting may be parsing your message in an unexpected way. I am therefore not able to help you with this issue.

When opening issues on GitHub, please do the following:
- Write a short paragraph of text explaining the issue you're running into, using complete sentences.
- Put a one-sentence summary of that paragraph in the issue title.
- Explain the necessary steps that should be taken to reproduce the issue, including how you obtained the program that the issue is occurring in, and its version.
- Communicate your expected program output and the program's actual output.
- Note the relevant operating system and software versions that you were using when you encountered this issue. For example, when reporting an issue for an npm package, it would make sense to include info such as OS, OS version, Node.js version, and npm version.
- Use GitHub's "preview" feature prior to submitting the issue to verify that your code is formatted correctly. You can consult [GitHub's "writing and formatting" documentation](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for help with how to get this right.

Please remember that most open-source software maintainers are not paid for creating and maintaining their open-source software; they create and share their projects as a hobby, in hopes that their creations can help others. They do not receive money when you use their product, and they do not receive money when you ask them for help, and they do not receive money when they help you. Be patient and courteous when communicating with them, and understand that because they have no obligation to help you, any help they provide is given out of the patience and kindness in their hearts.
